### ISSUE TITLE
FirefoxでのIMPORT欄の操作でフリーズすることがある

### ISSUE THREAD

**Issue by mikecat** [IchigoJam/web#17]
# 環境

* Windows 10 Home 22H2
* Firefox Browser 114.0.2 (64ビット)

# 再現手順

1. [IchigoJam web by jig.jp](https://fukuno.jig.jp/app/IchigoJam/) を開く
2. IMPORT用のテキストエリアをクリックし、フォーカスを当てる
3. キーボードの <kbd>a</kbd> キーを押す
4. もう一度キーボードの <kbd>a</kbd> キーを押す
5. 固まる

# 参考情報

https://github.com/IchigoJam/web/blob/9c7d1f14bb02eea909fffaf58ffa0acedfb3bef7/ichigojam.mjs#L1201-L1209

この部分で、`h` が 10、`lh` が 14 となりました。
すると、`h - lh` は負の値になり、不自然かもしれません。
`el.scrollHeight` と `el.offsetHeight` の値がともに 24 となっており、条件を満たさないため、無限ループになるようです。

**Comment by taisukef** [comment]
ありがとうございます！
MacのFirefoxでもフリーズ確認しました

**Comment by taisukef** [comment]
詳しく追いかけていませんが、ひとまず10回で抜けるように修正しました
