### ISSUE TITLE
RESETでプログラムの容量が回復しない

### ISSUE THREAD

**Issue by mikecat** [IchigoJam/web#19]
https://fukuno.jig.jp/app/IchigoJam/#10%20PRINT%20%22HELLO%2C%20WORLD%22%0ARESET%0A%3FFREE()%0A

プログラムを入力した後、`RESET` を実行し、`FREE()` の返り値を出力する。

1024 が出力されることを期待するが、1000 が出力される。

**Comment by taisukef** [comment]
ありがとうございます！
